kind: pipeline
type: docker
name: default

steps:
  - name: compile
    image: maven:3-jdk-11
    commands:
      - mvn compile
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn test
  - name: package
    image: maven:3-jdk-11
    commands:
      - mvn package -DskipTests
  - name: docker
    image: plugins/docker
    settings:
      repo: fmedisov/mse-backend
      username:
        from_secret: docker_username
      password:
        from_secret: docker_userpassword
      dockerfile: Dockerfile-packaged
      debug: true
      tags:
        - latest
        - v${DRONE_BUILD_NUMBER}
  - name: helm_deploy
    image: quay.io/ipedrazas/drone-helm
    settings:
      skip_tls_verify: true
      helm_repos: mse-repo=https://fmedisov.github.io/microservices-deploy/
      chart: mse-repo/mse-chart
      release: mse-project
      values: backend.image.tag=v${DRONE_BUILD_NUMBER}
      namespace: mse-ns
      debug: true
      secrets:
        - api_server
        - kubernetes_token
trigger:
  event:
    - push